### ISSUE TITLE
can't change viewport size

### ISSUE THREAD

**Issue by mohamedzajith** [jofftiquez/vue-croppie#12]
can you give me a sample code 
how can do that 
`this.$refs.logo({`
 `       viewport: {
        width: 150,
        height: 200
    }`
`});`
`this.$refs.logo.bind({`
 `       url:'http://i.imgur.com/Fq2DMeH.jpg'`
`});`

**Comment by jofftiquez** [comment]
Hello @mohamedzajith `viewport` is a props passed to the component, if you wish to change the view port put it on the component like` <vue-croppie v-bind:viewport=" { width: 150, height: 200 }"></vue-croppie>`

**Comment by jofftiquez** [comment]
For future questions you can go and chat me on our [gitter page](https://gitter.im/vue-croppie)
