### ISSUE TITLE
Unexpected token: punc()

### ISSUE THREAD

**Issue by LorrainInfinity** [jofftiquez/vue-croppie#13]
Hi.

I'm facing a weird problem due to this plugin.

I'm compiling my Vue files via Laravel Mix.  Every time I run the dev command, the scripts gets compilled successfully but when it comes to run the prod command (npm run production), I get an error linked to vue-croppie : Unexpected token: punc().

Do you know where it comes from ? 

Thank's!

**Comment by jofftiquez** [comment]
Hello @LorrainInfinity are you using `vue cli`? If yes please see [this guide](https://github.com/jofftiquez/morphling#debug) from my other project. The problem is related to the webpack configuration. For future questions please join our [gitter chat](https://gitter.im/vue-croppie/).
