### ISSUE TITLE
Bind should return  the croppie bind as it returns a promise

### ISSUE THREAD

**Issue by dobromir-hristov** [jofftiquez/vue-croppie#21]
As the title says, bind should really return the croppie bind value as its a promise and can be used as a ready callback. 
Alternative is to use `$ref.croppieElement.croppie.bind()` but that defeats the purpose of your function completely. 
I can do a PR if needed.

**Comment by jofftiquez** [comment]
Hi @dobromir-hristov PRs are much appreciated. Thank you.

**Comment by jofftiquez** [comment]
@dobromir-hristov Hi, did you submit a PR about this? I can't remember 😢I'm clearing issues now.

**Comment by dobromir-hristov** [comment]
I have not, can do it a bit later today

**Comment by jofftiquez** [comment]
@dobromir-hristov Alright. I'll just leave this open for now. Thank you!

**Comment by dobromir-hristov** [comment]
https://github.com/jofftiquez/vue-croppie/pull/23
