### ISSUE TITLE
The demo page is not working.

### ISSUE THREAD

**Issue by emilas44** [jofftiquez/vue-croppie#25]
Please fix the link:

https://jofftiquez.github.io/vue-croppie/

**Comment by jofftiquez** [comment]
Holy cr*p I didn't notice that. Thanks @emilas44 for reporting. I will fix this right away. 

[x ] Fix demo page
[ ] Create rollup build
[ ] Clean unused files

**Comment by emilas44** [comment]
And in your repository the demo/build.js file is missing!

**Comment by jofftiquez** [comment]
Right! Noted @emilas44 . Thanks.

**Comment by jofftiquez** [comment]
@emilas44 demo fixed!
