### ISSUE TITLE
Option to prevent automatic refresh() after every crop/result

### ISSUE THREAD

**Issue by cbaxter713** [jofftiquez/vue-croppie#29]
Is it possible to add in an option to prevent the automatic refresh() that is being called on each crop/result?  I would like the Croppie url that is bound to stay in place even after I evoke crop/result.

**Comment by jofftiquez** [comment]
@cbaxter713 Oh, I didn't think that it would be necessary. But you're right, there should be an option for that. I'll work on this over the weekend. Thanks.

**Comment by cbaxter713** [comment]
Awesome, thank you for doing that!

**Comment by jofftiquez** [comment]
@cbaxter713 Hi, I removed the auto refresh. You just have to call the `refresh()` function if you want to clear the canvas.

**Comment by cbaxter713** [comment]
Awesome, thanks for doing that
