### ISSUE TITLE
Add to Awesome-Vue List

### ISSUE THREAD

**Issue by brunogaspar** [jofftiquez/vue-croppie#3]
Hello @jofftiquez 

Consider adding your component to the [Awesome Vue.js List](https://github.com/vuejs/awesome-vue#image-manipulation) so you can have more people to know about your component and Croppie.

Thanks for the component :)

**Comment by jofftiquez** [comment]
@brunogaspar Wow, I didn't know there was such a list. Thank you for telling me. :) :100:

**Comment by brunogaspar** [comment]
No problem at all, just read their [contributing](https://github.com/vuejs/awesome-vue/blob/master/CONTRIBUTING.md) guide and submit a PR :)
