### ISSUE TITLE
Error on using into components.

### ISSUE THREAD

**Issue by zuxriddinkamalov** [jofftiquez/vue-croppie#31]
I'm using element-ui dialog. Into my dialog I defined croppie, but vue js can't see ref of croppie.

`<div id="profile_edit">
	<el-dialog
		@open="openCropWindow"
		width="600px"
		class="modal"
		title="Photo"
		:visible.sync="avatarModal">
		<vue-croppie 
			ref="croppieRef"
			:enable-resize="true"
			:mouse-wheel-zoom="false"
			:enable-orientation="true"
			:viewport="{ width: 200, height: 200, type: 'circle' }"
			@result="result">
		</vue-croppie>
	</el-dialog>
</div>
`

**Comment by jofftiquez** [comment]
It's because the component is not yet loaded inside the dialog component. If your dialog has a on-open event, add the vue-croppie component after that event.

**Comment by zuxriddinkamalov** [comment]
I resolved this problem with nextTick. On open dialog we can add this code:
   ```
this.$nextTick(function () {
        self.$refs.croppieRef.bind({
          url: base_url + self.logo,
        })
      })
```

**Comment by jofftiquez** [comment]
@zuxriddinkamalov nice!
