### ISSUE TITLE
Exif orientation fails

### ISSUE THREAD

**Issue by smesterheide** [jofftiquez/vue-croppie#34]
I am trying to make vue-croppie work with Exif orientation, but it fails. Possibly upstream related, but I wanted to try my luck here first.

Example fiddle: https://jsfiddle.net/50wL7mdz/479707/

**Comment by smesterheide** [comment]
Somehow enableExif does not work when enableOrientation is enabled at the same time. Setting it to false honers the Exif orientation and everything works as expected.

Beware that defaults in vue-croppie 1.3.12 differ from defaults in Croppie 2.6.1.

**Comment by jofftiquez** [comment]
@notapianokey thanks for noting the Croppie verion. I will update this repo for the new version. Take care!
