### ISSUE TITLE
Upload file problem

### ISSUE THREAD

**Issue by d1mapetrenko** [jofftiquez/vue-croppie#35]
Hi, when I'm try to upload image again I get error message if file not selected.
P.S: Sorry for my English.
![screenshot_1](https://user-images.githubusercontent.com/40215711/42685216-0e86b716-869b-11e8-91d8-188adb150ec5.png)
![screenshot_2](https://user-images.githubusercontent.com/40215711/42685217-0ea5bd0a-869b-11e8-976d-c6d6892ea56d.png)
![screenshot_3](https://user-images.githubusercontent.com/40215711/42685218-0ec30a7c-869b-11e8-920f-f04c46ce4497.png)

**Comment by jofftiquez** [comment]
Hi @d1mapetrenko I believe you should open this issue in official [Croppie repository](https://github.com/foliotek/croppie).
