### ISSUE TITLE
Get File from input 

### ISSUE THREAD

**Issue by lord-zeus** [jofftiquez/vue-croppie#37]
hey @jofftiquez how can i get the image from an input rather than the url please

**Comment by jofftiquez** [comment]
Hello @lord-zeus I might have to close this coz this is not an issue with the plugin. But I can help you with your question. Normally you'd use an input with type `file`. 

Here are some implementations. 

https://stackoverflow.com/a/34840295

https://www.html5rocks.com/en/tutorials/file/dndfiles/

**Comment by lord-zeus** [comment]
Thanks

[u had already solved the my problem here](https://github.com/jofftiquez/vue-croppie/issues/4)

**Comment by jofftiquez** [comment]
@lord-zeus Great!
