### ISSUE TITLE
Getting Uncaught RangeError: Maximum call stack size exceeded Error

### ISSUE THREAD

**Issue by sureshp83** [jofftiquez/vue-croppie#39]
HI, I am getting  Uncaught RangeError: Maximum call stack size exceeded. please give me correct solution ASAP.
here is error screenshot.
 
![screenshot from 2018-08-22 09 41 44](https://user-images.githubusercontent.com/41883580/44442431-cd019580-a5ef-11e8-94cb-a26d0e6418e1.png)
i use same code as you posted on github. please let me know any solutions.

**Comment by jofftiquez** [comment]
@sureshp83 Please use proper formatting and perhaps a screenshot of the error. I cannot help you with this kind of issue formatting. Will re-open once you properly formatted the issue. Also please add the error, to make sure that the error is from VueCroppie. Best! Thanks.

**Comment by sureshp83** [comment]
I changed my post please check it.
   On Tuesday, August 21, 2018, 10:19:36 PM GMT+5:30, Jofferson Ramirez Tiquez <notifications@github.com> wrote:  
 
 
@sureshp83 Please use proper formatting and perhaps a screenshot of the error. I cannot help you with this kind of issue formatting. Will re-open once you properly formatted the issue. Also please add the error, to make sure that the error is from VueCroppie. Best! Thanks.
