### ISSUE TITLE
how can we use image upload ? i need to choose image file and do crop on that particular image.

### ISSUE THREAD

**Issue by sureshp83** [jofftiquez/vue-croppie#40]
Hi, I need to use cropping on my selected images, not default image? how can do? please tell me a step.

**Comment by jofftiquez** [comment]
Hi @sureshp83 

First create an input with type `file` this should emit a file data of the image. Then add the `file` to `vue-croppie` using the `.bind()` method.

**Comment by notedboi** [comment]
@sureshp83  Or use ` let url = window.URL.createObjectURL(fileList[0])` to get url of local file, pass the url either to `.bind()` or to `.filesChange()`

**Comment by stsposoh** [comment]
Hi! I have the same trouble. Could you explain more fully?
"Then add the file to vue-croppie using the .bind() method." - how can I do that?

**Comment by jofftiquez** [comment]
Closing now. Kindly re-open if you have more concern.

**Comment by guumaster** [comment]
I've been playing with `vue-croppie` and made an app to upload / modify / download. You can check it here: https://rolodromo.github.io/playground-token-maker/

**Comment by jofftiquez** [comment]
@guumaster that's a nice project. Thanks for using `vue-croppie` :)
