### ISSUE TITLE
maxZoom option not supported via a prop

### ISSUE THREAD

**Issue by pocketarc** [jofftiquez/vue-croppie#44]
There are two options, minZoom and maxZoom, which are not supported by vue-croppie.

I'm just leaving this as a note here for the devs; I've made the appropriate change on my side and will be packaging it up properly as a PR, if that's alright with you!

**Comment by jofftiquez** [comment]
@BrunoDeBarros a PR is very much welcome :)

**Comment by dobromir-hristov** [comment]
@BrunoDeBarros do you need help with that PR? I can submit a PR too, but you said you have already done it.

**Comment by jofftiquez** [comment]
Hi @dobromir-hristov it seems @BrunoDeBarros wasn't able to push a PR, you can submit yours. Thank you.
