### ISSUE TITLE
CORS issues when binding images. 

### ISSUE THREAD

**Issue by donnie24** [jofftiquez/vue-croppie#45]
Do you have any solution abut CORS issue? Thanks

**Comment by jofftiquez** [comment]
Are you trying to bind an image from a url?

**Comment by donnie24** [comment]
Yes, im try to bind an image let say from s3 server.

**Comment by jofftiquez** [comment]
Maybe your s3 server cors configuration is blocking the localhost? In my demo, those images are also from an online url.

**Comment by donnie24** [comment]
in the s3 configuration is already set. i will provide image url and try to test. 
Try this url https://fdca.s3-ap-southeast-2.amazonaws.com/c23d8a72-21f6-4c19-bad3-93601011ca42.jpg

thanks

**Comment by jofftiquez** [comment]
@donnie24 I was able to bind the image look here. http://vue-croppie.surge.sh/

How do you server you localhost enviroment?

**Comment by jofftiquez** [comment]
I will close this issue now because the problem is not within the plugin. You can still ask questions related to this issue here. I will see what I can help you with.
