### ISSUE TITLE
Console error on using chrome

### ISSUE THREAD

**Issue by koujiuji** [jofftiquez/vue-croppie#57]
Hi! I like your works:)

In using chrome browser, when start to crop and dragging image, following errros are outputed.

```
index.js:1088 Unable to preventDefault inside passive event listener invocation.
function mouseDown(ev)

index.js:1110 Unable to preventDefault inside passive event listener invocation.
function mouseMove(ev)
```

The cause is refer to this link, chrome ignore calling preventDefault.
https://www.chromestatus.com/features/5093566007214080

So please add explicitly {passive: false} of options on next version.
```
ex) 
dist/index.js :727
window.addEventListener('mousemove', mouseMove, { passive: false });
```

Best Regards!

**Comment by dobromir-hristov** [comment]
This is connected to crippie it self. You are free to make a PR there.

**Comment by koujiogawa** [comment]
Thanks reply, I found work around for this issue, so please close this ticket.
Best, Koji
