### ISSUE TITLE
Promises for bound function

### ISSUE THREAD

**Issue by nicolasvahidzein** [jofftiquez/vue-croppie#6]
Hello again Joff,

i think there might be the same bug with bind this time, i'm trying to get the result immediately after the bound function is successful but i can't get it to trigger:
```
                                                this.$refs.croppieRef.bind({url: reader.result}, output => {
							//this should trigger once the image has been loaded successfully
							
							this.$refs.croppieRef.result({format: 'base64', circle: false}, result => {	
								//here i save the image info
							})
						})
```

**Comment by nicolasvahidzein** [comment]
i'm so proud of myself, i think i fixed it, i don't know how to do those pull request people speak of on github, maybe you can show me, but here is the fix
```
               bind(options, cb) {
                    this.croppie.bind(options).then(output => {
                        cb(output);
                    });
                },
```
instead of this:
```
               bind(options) {
                    this.croppie.bind(options)
                },
```

**Comment by jofftiquez** [comment]
Hi @nicolasvahidzein nice solution. However the whole point of the bind() function is to bind an image to the croppie and not to get the cropped result. That's why there is a separate method for he crop action. But let's see what we can work around to improve this project.

**Comment by nicolasvahidzein** [comment]
true but it's not so much about the result as much as the function telling you when the image is loaded so you can do an async action. Otherwise you are kind of screwed since you don't know when your image has loaded. Not sure if i am making any sense.

**Comment by jofftiquez** [comment]
@nicolasvahidzein In that case you I can consider passing the loaded image in the callback, but not the "cropped" version.

**Comment by nicolasvahidzein** [comment]
You mean bind? You have a snippet by any chance?

**Comment by jofftiquez** [comment]
Hello @nicolasvahidzein upon careful consideration I came to the conclusion to not add a callback for `bind()` funtion, this is because you already have the image before you bind it in the first place. Thanks always Nic!

**Comment by nicolasvahidzein** [comment]
No problem, thanks Joff. I do think a callback is great because we have operations we might want to do right after. But you are the boss.
