### ISSUE TITLE
enableOrientation & enableExif

### ISSUE THREAD

**Issue by adabutch** [jofftiquez/vue-croppie#60]
I'm using this component via a file input with Nuxtjs like:

```
<no-ssr>
<vue-croppie
    ref="croppieRef"
    :enableExif="true"
    :enableOrientation="true"
    :enableResize="false"
    :showZoomer="true"
    @update="update"
    :viewport="{ width: 180, height: 240 }"
    :boundary="{ width: 180, height: 240 }" />
</no-ssr>
```
I'm using EXIF.js to get the image orientation. However, it seems to do nothing. I would like the photo uploaded to automatically rotate to the correct orientation within the `croppieRef` above. 

I can post more code if that's helpful, not sure if others are experiencing an issue(s) w/ this, or I'm setting things up wrong ... thought I'd ask the community for an appreciated hand. Thanks!

**Comment by dobromir-hristov** [comment]
Please post a properly reproducible link to your issue. From this code, you are just showing the croppie plugin.
