### ISSUE TITLE
enableOrientation, enableResize set in props vue-croppie no working!

### ISSUE THREAD

**Issue by rukadh2** [jofftiquez/vue-croppie#63]
I have code :
vue-croppie(ref='croppieRef', :enableOrientation="false", :enableResize="false"

Error: enableResize = false, vue-croppie not working.

I tried:
Replace all "enableOrientation" and "enableResize" in file vue-croppie.js
=> Result: enableResize and enableOrientation working [OK]

P/S: sorry my english is not good

**Comment by jofftiquez** [comment]
Hi @rukadh2 can you show me the actual screenshot of the error? Thanks.

**Comment by rukadh2** [comment]
I tried:
Replace all: "enableOrientation" and "enableResize" in file vue-croppie.js
enableOrientation => enableorientation
enableResize => enableresize

=> Result: [OK]

**ERR**
![Err](https://user-images.githubusercontent.com/35477249/58340115-4ecf6980-7e75-11e9-8d1a-7e5b0d4d20bb.png)

**FIX**
![Fix](https://user-images.githubusercontent.com/35477249/58340131-555de100-7e75-11e9-9416-954fa9d7a052.png)

**Comment by jofftiquez** [comment]
Got it. Thanks.

**Comment by jofftiquez** [comment]
Are you using single file component?

**Comment by rukadh2** [comment]
Yes!

This file is https://github.com/jofftiquez/vue-croppie/blob/master/dist/vue-croppie.js
