### ISSUE TITLE
No Image at startup

### ISSUE THREAD

**Issue by audetcameron** [jofftiquez/vue-croppie#72]
This is what I see on load
https://codesandbox.io/s/9l5oyll1yy?from-embed

it appears $refs.croppieRef.bind  no  longer works.

adding 
    :boundary="{ width: 300, height: 300}"
     :viewport="{ width: 230, height: 230 , type: 'circle'}"
worked. i think

**Comment by audetcameron** [comment]
I also get  Cannot read property 'bind' of undefined  when using this in mounted
```
                this.$refs.croppieRef.bind({
                    url: 'http://i.imgur.com/Fq2DMeH.jpg',
                })  
```

**Comment by jofftiquez** [comment]
Hello @audetcameron the bind function is working. It's just that the boundary is not set that's why there's nothing at the beginning. I updated the docs. Thanks for this!
