### ISSUE TITLE
croppieInitialized isn't working

### ISSUE THREAD

**Issue by german-swan** [jofftiquez/vue-croppie#73]
I don't see any entries for 'croppieInitialized', why did you write about this event in your README.md and how can I know when croppie became initialized?

**Comment by matthewboman** [comment]
If you look at [https://github.com/jofftiquez/vue-croppie/blob/master/index.html](url) it is

    croppieInitialized() {
          // This method will be executed when the croppie is initialized
           // You can use it to set the image
           // this.$refs.croppieRef.bind({
           //   url: 'http://i.imgur.com/Fv2YOM6.jpg',
           // });
           console.log('Croppie was initialized');
         }`

Not sure why this was left out of the example.

**Comment by jofftiquez** [comment]
`croppieInitialized` is not an event. It's a prop. https://github.com/jofftiquez/vue-croppie/blob/2d671938ad04e3266e2acd8292c17457d8d0d498/src/VueCroppieComponent.js#L40
