### ISSUE TITLE
On change event emitters

### ISSUE THREAD

**Issue by nicolasvahidzein** [jofftiquez/vue-croppie#8]
Joff, the on change event emitters that are present in the original croppie are they here too?

How do i listen to those? i saw you added your own event listeners but those are not the ones that are triggered when a user moves an image or zooms in and out. 

Is this working in vue-croppie?

**Comment by jofftiquez** [comment]
@nicolasvahidzein I'll start working on this. For the meantime, if you have questions please go to vue-croppie's gitter https://gitter.im/vue-croppie/
