### ISSUE TITLE
Issues with low quality images & a bug with multiple result query

### ISSUE THREAD

**Issue by nicolasvahidzein** [jofftiquez/vue-croppie#9]
Hello Joff,

you need to see this behavior.

I figured out that low quality images do not produce normal crops, and i don't know if it's due to the update you did because of me but now, when you pull a second result() query based on promises, it comes up null like so:   "data:,"

hit me up, i can do a tv session to show you.

**Comment by nicolasvahidzein** [comment]
Ok after a lot of digging on croppie there was a lonely comment that was very important for the annoying bad file size and quality issue:

https://github.com/Foliotek/Croppie/issues/297

As BassT says:

Try calling result with {type: 'base64', size: 'viewport'}. Then you should always get the right size.

**Comment by nicolasvahidzein** [comment]
The empty result still stands though.

**Comment by jofftiquez** [comment]
I'll try to digin the empty result bug. However can you create a reproduction of the bug? Perhaps on a JsFiddle or a video recording on how you produced it? That'll help me a lot to fix things.

**Comment by nicolasvahidzein** [comment]
Ok here is the link to the file itself, but let me explain first here so you don't waste too much time digging through all my lines. PS if you can coach me on how to use OOP or polymorphism in this instance that would be nice, i am using a lot of switches but it making it huge.

i'm sending the 2 links via Gitter.

Ok so this is the most important function:    cameraSectionProcessImageData

it get's called everytime i need to save the image data. I call it actually only 3 times. The first time the user loads an image. When he crops an image, and when he saves an image. Let me explain why, some users are lazy or do not know and thus might not crop before saving an image, so i want to avoid bugs and angry users. Also a user can move an image and zoom and again not click, so that is why i generate on save again that way they don't even have to press crop. Now for those who crop like good boys and girls, they are doing it right, sad thing, in this last and best instance, the result returns empty data like so: 'data, '. so i had to do a trick by querying the result, if it's empty, use the previous saved image data inside vmodel and use that instead. If it's not blank, use the most recent non empty result query. SO here goes:

```
cameraSectionProcessImageData: function (method = null) {
	if (store.state.traceDebug === true) {
		console.log('cameraSectionProcessImageData function in CreateIndividual.vue')
	}
	
	this.$refs.croppieRef.result({format: 'base64', size: 'viewport'}, result => {
		
		console.log('result inside the on upload sequence')
		console.log('result at the top')
		if (result === 'data:,') {
			console.log('NO DATA:')
			console.log(result)
		} else {
			console.log('IMAGE DATA IS PRESENT:')
		}
		
		if (method === null) {
			console.log('method is null')
			this.imagefield = result
			// this.imageFileChosen()
			
		} else {
			console.log('method is NOT null - we are pulling the data and then saving it')
			// console.log(this.imagefield)
			
			var tempImagefield
			
			if (result === 'data:,') {
				console.log('NO DATA:')
				console.log(result)
				
				// no let's take query the old image data we have not yet overwritten
				
				if (this.imagefield === 'data:,' || this.imagefield === null) {
					console.log('nope it seems imagefield data is also unuseable')
				} else {
					console.log('ok its useable')
					tempImagefield = this.imagefield
				}
				
				
				
			} else {
				console.log('IMAGE DATA IS PRESENT:')
				tempImagefield = result
			}
			
			// this.imagefield = result
			// this.imageFileChosen()
			// console.log(this.imagefield)
			
			//we need a temp variable because since it is async the imagefield var gets erased by the preparesuccessor function that is not async and moves automatically in cleaning up the data from the previous module
			
			this.imageFields.push({ item: this.item_image, value: tempImagefield/*this.imagefield*/, UID: this.fieldUID.toString(), showOptions: false })
			
			this.createdFields.push({ item: this.item_image, UID: this.fieldUID.toString() })
		}
		
	})
},
```

and this is inside my processEntry function where i add the item
```
case this.item_image:
	console.log('process entry function')
	//we reprocess the image because maybe the user doens't know or want to crop the image and leaves it as is
	this.cameraSectionProcessImageData('submit')
	console.log('after cameraSectionProcessImageData function was called, this is the middle of the process entry function')
	//this usual saving of data that is done here is now done in the async portion of this function: cameraSectionProcessImageData()
	
	//find a way to check if the stream is open or not and then stop it
	this.webcamMediaStream.stop()
	
	break
```

**Comment by jofftiquez** [comment]
Hello @nicolasvahidzein I'll close this issue now for inactivity. I suggest you update to the latest version of vue-croppie :) Please don't hesitate to ask for help. Thank you.
